# Generated by Django 6.0.3 on 2026-03-11 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_funds', 'Added Funds'), ('withdraw_funds', 'Withdrawn Funds'), ('suspend_account', 'Suspended Account'), ('activate_account', 'Activated Account'), ('approve_refund', 'Approved Refund'), ('reject_refund', 'Rejected Refund')], max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
