# Generated by Django 5.2.12 on 2026-03-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('resident_permit', 'Resident Permit')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
