# Generated by Django 5.2.12 on 2026-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_id_back_userprofile_id_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
