# Generated by Django 5.2.12 on 2026-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('USA', 'United States'), ('Canada', 'Canada'), ('Other', 'Other')], default='USA', max_length=10),
        ),
    ]
