# Generated by Django 5.2.12 on 2026-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('USA', 'United States (USD, $)'), ('Canada', 'Canada (CAD, $)'), ('UK', 'United Kingdom (GBP, £)'), ('AU', 'Australia (AUD, $)'), ('DE', 'Germany (EUR, €)'), ('FR', 'France (EUR, €)'), ('IT', 'Italy (EUR, €)'), ('ES', 'Spain (EUR, €)'), ('JP', 'Japan (JPY, ¥)'), ('CN', 'China (CNY, ¥)'), ('IN', 'India (INR, ₹)'), ('BR', 'Brazil (BRL, R$)'), ('MX', 'Mexico (MXN, $)'), ('KR', 'South Korea (KRW, ₩)'), ('SG', 'Singapore (SGD, $)'), ('CH', 'Switzerland (CHF)'), ('NZ', 'New Zealand (NZD, $)'), ('AR', 'Argentina (ARS, $)'), ('ID', 'Indonesia (IDR, Rp)'), ('SA', 'Saudi Arabia (SAR, ﷼)'), ('Other', 'Other (USD, $)')], default='USA', max_length=10),
        ),
    ]
